# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0002_auto_20180416_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('cromo_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='test_project.Cromo')),
                ('posicion', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('club', models.CharField(max_length=40)),
                ('altura', models.CharField(max_length=10)),
                ('peso', models.CharField(max_length=10)),
                ('debut', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pagina',
            name='tipo',
            field=models.CharField(choices=[('Pais', 'Pais'), ('MS', 'Miscaleneo')], default='Pais', max_length=30),
        ),
    ]
