# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0003_auto_20180416_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cromo',
            name='descripcion_text',
        ),
    ]
