# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cromo_list',
        ),
    ]
