# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0006_remove_userprofile_cromo_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Cromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetido', models.IntegerField()),
                ('cromo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_project.Cromo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_project.UserProfile')),
            ],
        ),
    ]
