# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0007_list_cromo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_cromo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
