# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0008_auto_20180418_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cromo_Rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cromo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_project.Cromo')),
            ],
        ),
        migrations.RemoveField(
            model_name='list_cromo',
            name='cromo_id',
        ),
        migrations.RemoveField(
            model_name='list_cromo',
            name='repetido',
        ),
        migrations.AlterField(
            model_name='list_cromo',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cromo_rep',
            name='list_cromo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_project.List_Cromo'),
        ),
    ]
