# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0009_auto_20180418_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='cromo_rep',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
