# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0010_cromo_rep_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cromo_rep',
            name='cromo_id',
        ),
        migrations.AddField(
            model_name='cromo',
            name='cromo_rep',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='test_project.Cromo_Rep'),
        ),
    ]
