# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0014_auto_20180418_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cromo',
            name='cromo_rep',
        ),
        migrations.AddField(
            model_name='cromo_rep',
            name='cromo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='test_project.Cromo'),
            preserve_default=False,
        ),
    ]
