# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0015_auto_20180418_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cromo_rep',
            name='no_repeat',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>', max_length=30),
        ),
    ]
