# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0016_cromo_rep_no_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cromo_rep',
            name='no_repeat',
            field=models.CharField(max_length=30),
        ),
    ]
