# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-24 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0018_auto_20180418_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='num_sobres',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='time_sobres',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
