# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-25 04:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0020_auto_20180624_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='time_sobres',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 25, 4, 47, 29, 775395, tzinfo=utc)),
        ),
    ]
